#!/usr/bin/env python3
"""Compile canonical command sources into per-harness targets.

    commands/<name>.md  ->  .claude/commands/<name>.md        (Claude Code)
                            .agents/skills/<name>/SKILL.md    (Antigravity)

A pure, deterministic build: same inputs, byte-identical outputs, no
timestamps, no machine-specific state.

Pipeline:
  1. Load + validate commands/*.md.
  2. Parse frontmatter (description, argument-hint, allowed-tools).
  3. Derive execution mode (kind: exec vs kind: prompt) from body.
  4. Emit Claude Code targets (.claude/commands/<name>.md) with byte-identical
     formatting and no generated marker.
  5. Emit Antigravity skill targets (.agents/skills/<name>/SKILL.md) with
     GENERATED marker and hardened execution semantics for exec mode.
  6. Sanitize before write: refuse to emit anything carrying a
     secret-like string or a local home path.
  7. Prune unmanaged targets while respecting the wrap.md allowlist.

Usage:
  python3 scripts/sync_commands.py            build into repo
  python3 scripts/sync_commands.py --check    rebuild and diff against disk;
                                              exit 1 on drift
  python3 scripts/sync_commands.py --root DIR --out DIR
                                              compile an alternate source
                                              tree into an alternate
                                              output tree (roundtrip test)
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("ERROR: pyyaml is not installed (pip install pyyaml).")


MARKER = "GENERATED by scripts/sync_commands.py — edit commands/, not this file"

CLAUDE_TARGET_DIR = ".claude/commands"
AGENTS_TARGET_DIR = ".agents/skills"

ALLOWLIST_CLAUDE_FILES = {"wrap.md", "claim.md", "fast.md", "release.md"}

# Import SECRET_PATTERNS directly from sync_agents (D8, R1-9) to guarantee zero sanitizer drift
try:
    from scripts.sync_agents import SECRET_PATTERNS as _AGENT_SECRET_PATTERNS  # type: ignore
except ImportError:
    try:
        from sync_agents import SECRET_PATTERNS as _AGENT_SECRET_PATTERNS  # type: ignore
    except ImportError:
        import sys
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
        from scripts.sync_agents import SECRET_PATTERNS as _AGENT_SECRET_PATTERNS  # type: ignore

SECRET_PATTERNS: list[tuple[re.Pattern[str], str]] = list(_AGENT_SECRET_PATTERNS)

for _literal in filter(
    None,
    (
        s.strip()
        for s in (
            os.environ.get("SYNC_COMMANDS_DENY", "")
            or os.environ.get("SYNC_AGENTS_DENY", "")
        ).split(",")
    ),
):
    SECRET_PATTERNS.append(
        (re.compile(re.escape(_literal), re.IGNORECASE), "denied local string")
    )



class BuildError(Exception):
    """A source or config problem the operator must fix."""


class CommandSource:
    def __init__(
        self,
        name: str,
        path: Path,
        raw_content: str,
        frontmatter_dict: dict,
        description_raw: str,
        argument_hint_raw: str | None,
        allowed_tools_raw: str | None,
        body: str,
        kind: str,
    ):
        self.name = name
        self.path = path
        self.raw_content = raw_content
        self.frontmatter_dict = frontmatter_dict
        self.description_raw = description_raw
        self.argument_hint_raw = argument_hint_raw
        self.allowed_tools_raw = allowed_tools_raw
        self.body = body
        self.kind = kind  # "exec" or "prompt"


def load_command(path: Path) -> CommandSource:
    content = path.read_text(encoding="utf-8")
    if not content.startswith("---\n"):
        raise BuildError(f"{path}: missing opening frontmatter delimiter '---'")

    parts = content.split("---\n", 2)
    if len(parts) < 3:
        raise BuildError(f"{path}: malformed frontmatter (fewer than 2 delimiters)")

    fm_text = parts[1]
    body = parts[2]

    try:
        fm_dict = yaml.safe_load(fm_text)
    except yaml.YAMLError as exc:
        raise BuildError(f"{path}: frontmatter is not valid YAML: {exc}") from exc

    if not isinstance(fm_dict, dict):
        raise BuildError(f"{path}: frontmatter must be a YAML mapping")

    description = fm_dict.get("description")
    if not description or not str(description).strip():
        raise BuildError(f"{path}: missing or empty 'description' in frontmatter")

    # Extract raw scalar representations to prevent YAML reflowing
    desc_match = re.search(r"^description:\s*(.+)$", fm_text, re.MULTILINE)
    description_raw = desc_match.group(1).strip() if desc_match else str(description)

    arg_match = re.search(r"^argument-hint:\s*(.+)$", fm_text, re.MULTILINE)
    argument_hint_raw = arg_match.group(1).strip() if arg_match else None

    tools_match = re.search(r"^allowed-tools:\s*(.+)$", fm_text, re.MULTILINE)
    allowed_tools_raw = tools_match.group(1).strip() if tools_match else None

    # Derive kind: exec vs prompt (D3)
    # Check the first non-whitespace line of body
    body_stripped_lines = [line for line in body.splitlines() if line.strip()]
    if body_stripped_lines and body_stripped_lines[0].strip().startswith("!"):
        kind = "exec"
    else:
        kind = "prompt"

    return CommandSource(
        name=path.stem,
        path=path,
        raw_content=content,
        frontmatter_dict=fm_dict,
        description_raw=description_raw,
        argument_hint_raw=argument_hint_raw,
        allowed_tools_raw=allowed_tools_raw,
        body=body,
        kind=kind,
    )


def load_all_commands(root: Path) -> list[CommandSource]:
    commands_dir = root / "commands"
    if not commands_dir.is_dir():
        return []
    sources = []
    for path in sorted(commands_dir.glob("*.md")):
        sources.append(load_command(path))
    return sources


# --- Emitters -----------------------------------------------------------------


def emit_claude(cmd: CommandSource) -> str:
    """Emit .claude/commands/<name>.md matching origin/main byte-for-byte."""
    lines = ["---", f"description: {cmd.description_raw}"]
    if cmd.argument_hint_raw is not None:
        lines.append(f"argument-hint: {cmd.argument_hint_raw}")
    if cmd.allowed_tools_raw is not None:
        lines.append(f"allowed-tools: {cmd.allowed_tools_raw}")
    lines.append("---")
    lines.append("")

    # Validate that emitted frontmatter round-trips with parsed dict (R1-5)
    emitted_fm = "\n".join(lines[1:-2])
    try:
        re_parsed = yaml.safe_load(emitted_fm)
    except Exception as exc:
        raise BuildError(f"{cmd.path}: emitted Claude frontmatter failed to parse: {exc}") from exc
    if re_parsed != cmd.frontmatter_dict:
        raise BuildError(
            f"{cmd.path}: frontmatter failed roundtrip validation: {re_parsed} != {cmd.frontmatter_dict}. "
            "The verbatim emitter could not accurately represent all frontmatter keys/values."
        )

    return "\n".join(lines) + cmd.body


def emit_antigravity(cmd: CommandSource) -> str:
    """Emit .agents/skills/<name>/SKILL.md with hardened execution semantics."""
    lines = [
        "---",
        f"# {MARKER}",
        f"name: {cmd.name}",
        f"description: {cmd.description_raw}",
        "---",
        "",
    ]

    if cmd.kind == "exec":
        # Refuse exec commands whose hooks are not explicitly supported (R1-4)
        if cmd.name != "work":
            raise BuildError(
                f"{cmd.path}: unsupported exec command '{cmd.name}': "
                "compiler only supports hardened exec semantics for 'work'"
            )

        # Unpack the ! expression and emit hardened instructions (D5, R1-3)
        # Find any guidance lines after the ! expression line
        body_lines = cmd.body.splitlines(keepends=True)
        rest_lines = []
        found_exec_line = False
        for line in body_lines:
            if not found_exec_line and line.strip().startswith("!"):
                found_exec_line = True
                continue
            if found_exec_line:
                rest_lines.append(line)

        instructions = [
            "When executing this command:",
            "",
            "1. Validate input shape:",
            "   - Guided mode (default): `[<number>]`",
            "   - Unattended mode (opt-in): `<number> [--as <persona>]` (when `--yolo` is specified)",
            "   Where `<number>`, if provided, contains only digits.",
            "2. Strictly reject any input containing shell metacharacters: `;`, `&`, `|`, `` ` ``, `$`, `(`, `)`, `<`, `>`, `\\n`.",
            "3. Dispatch based on mode:",
            "   - If `--yolo` is specified: Invoke `HEADLESS=1 scripts/ops/work.sh <number> [--as <persona>]` via `run_command` and report output.",
            "   - In guided mode (no `--yolo`): Invoke `scripts/ops/work_dispatch.sh [<number>]` via `run_command`. Do NOT shell out to `scripts/ops/work.sh` in this mode; follow the guided steps below.",
            "",
        ]
        return "\n".join(lines) + "\n".join(instructions) + "".join(rest_lines).lstrip()
    else:
        # Prompt mode retains canonical prompt instructions (D6)
        # allowed-tools is omitted from frontmatter
        return "\n".join(lines) + cmd.body



def sanitize(relpath: str, content: str) -> None:
    for pattern, label in SECRET_PATTERNS:
        match = pattern.search(content)
        if match:
            line = content[: match.start()].count("\n") + 1
            raise BuildError(
                f"REFUSING TO WRITE {relpath}: line {line} looks like a "
                f"{label} ({match.group(0)[:24]!r}). Fix the source under "
                f"commands/ — the compiler never emits it."
            )
    if any(pattern.search(relpath) for pattern, _ in SECRET_PATTERNS):
        raise BuildError(f"REFUSING TO WRITE {relpath}: output path looks unsafe.")


def compile_all(root: Path) -> dict[str, str]:
    commands = load_all_commands(root)
    files: dict[str, str] = {}
    for cmd in commands:
        claude_path = f"{CLAUDE_TARGET_DIR}/{cmd.name}.md"
        claude_content = emit_claude(cmd)
        sanitize(claude_path, claude_content)
        files[claude_path] = claude_content

        agy_path = f"{AGENTS_TARGET_DIR}/{cmd.name}/SKILL.md"
        agy_content = emit_antigravity(cmd)
        sanitize(agy_path, agy_content)
        files[agy_path] = agy_content

    return files


def existing_managed(out: Path) -> dict[str, str]:
    """Find existing targets managed by sync_commands.py."""
    found: dict[str, str] = {}

    # 1. Claude commands: all *.md files directly in .claude/commands
    claude_dir = out / CLAUDE_TARGET_DIR
    if claude_dir.is_dir():
        for path in sorted(claude_dir.glob("*.md")):
            if path.name in ALLOWLIST_CLAUDE_FILES:
                continue
            try:
                content = path.read_text(encoding="utf-8")
                found[f"{CLAUDE_TARGET_DIR}/{path.name}"] = content
            except UnicodeDecodeError:
                continue

    # 2. Antigravity skills: .agents/skills/<name>/SKILL.md with MARKER
    skills_dir = out / AGENTS_TARGET_DIR
    if skills_dir.is_dir():
        for skill_file in sorted(skills_dir.glob("*/SKILL.md")):
            try:
                content = skill_file.read_text(encoding="utf-8")
                if MARKER in content:
                    relpath = f"{AGENTS_TARGET_DIR}/{skill_file.parent.name}/SKILL.md"
                    found[relpath] = content
            except UnicodeDecodeError:
                continue

    return found


def write(files: dict[str, str], out: Path) -> tuple[int, int, int]:
    managed = existing_managed(out)
    stale = set(managed) - set(files)
    written = unchanged = 0

    for relpath, content in files.items():
        path = out / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            unchanged += 1
            continue
        path.write_text(content, encoding="utf-8")
        written += 1

    for relpath in sorted(stale):
        (out / relpath).unlink()

    # Clean empty skill directories
    skills_dir = out / AGENTS_TARGET_DIR
    if skills_dir.is_dir():
        for path in sorted(skills_dir.glob("*"), reverse=True):
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()

    return written, unchanged, len(stale)


def check(files: dict[str, str], out: Path) -> int:
    committed = existing_managed(out)
    drift: list[str] = []

    for relpath, content in files.items():
        if relpath not in committed:
            drift.append(f"  MISSING   {relpath} (never committed)")
        elif committed[relpath] != content:
            drift.append(f"  STALE     {relpath} (committed copy differs)")

    for relpath in sorted(set(committed) - set(files)):
        drift.append(f"  ORPHANED  {relpath} (no source emits it)")

    if drift:
        print("DRIFT: compiled command targets do not match commands/:")
        print("\n".join(sorted(drift)))
        print("\nRun: python3 scripts/sync_commands.py  — then commit the result.")
        return 1

    print(f"OK: {len(files)} compiled command targets match commands/.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="diff fresh build against disk without writing; exit 1 on drift",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="repository root (default: repo containing scripts/)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output root (default: same as --root)",
    )

    args = parser.parse_args()
    root = args.root.resolve()
    out = (args.out or root).resolve()

    try:
        files = compile_all(root)
    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.check:
        return check(files, out)

    written, unchanged, pruned = write(files, out)
    print(
        f"sync_commands: {written} written, {unchanged} unchanged, "
        f"{pruned} pruned across 2 harnesses."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
