#!/usr/bin/env python3
"""Compile canonical persona sources into per-harness agent targets.

    personas/ + config/  ->  .claude/agents/        (Claude Code)
                             .agents/agents/<name>/ (Antigravity)

A pure, deterministic build: same inputs, byte-identical outputs, no
timestamps, no machine-specific state. That is what lets the drift gate
(#6) be nothing more than "rebuild and diff".

Pipeline, per persona x per harness:

  1. Load + validate every personas/*.yaml against personas/schema.json.
  2. Resolve the three lookups that live in config/ — the only layer
     where vendor names appear: tier -> model (model_tiers.yaml),
     persona -> harness (deployments.yaml), capability -> tools
     (tools.yaml).
  3. Assemble one instruction body: role contract, inlined skills in
     declared order, authority statement, a pointer to AGENTS.md
     (referenced, never duplicated), and generated fallbacks for
     optional capabilities the harness cannot map.
  4. Emit through one small emitter per harness. Adding a harness is
     adding one emitter and touching zero persona sources.
  5. Sanitize before write: refuse to emit anything carrying a
     secret-like string or a local home path.

Which targets get emitted (#5 D2 as amended 2026-09-10):
  * every source, persona or sub-agent, compiles for EVERY harness, so
    any persona can be started interactively on either harness. The
    pin in config/deployments.yaml is workflow glue — it tells the
    dispatcher which harness launches the persona unattended — and is
    validated here, but it never limits where the definition exists.

Usage:
  python3 scripts/sync_agents.py            build into the repo
  python3 scripts/sync_agents.py --check    rebuild and diff against the
                                            committed targets without
                                            touching them; exit 1 on drift
  python3 scripts/sync_agents.py --verify   re-parse the emitted targets
                                            and assert each carries its
                                            resolved model, mapped tools
                                            and full skill text
  python3 scripts/sync_agents.py --root DIR --out DIR
                                            compile an alternate source
                                            tree into an alternate
                                            output tree (roundtrip test)

Environment: SYNC_AGENTS_DENY is an optional comma-separated list of
site-specific strings the sanitizer must also refuse (a local account
name, an internal domain). It is passed in at run time and never
committed — writing the thing you are hiding into a public repository
defeats the check.

Dependencies: stdlib + pyyaml + jsonschema. Nothing else.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import textwrap
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - dependency failure is a hard stop
    sys.exit("ERROR: pyyaml is not installed (pip install pyyaml jsonschema).")

try:
    import jsonschema
except ImportError:  # pragma: no cover - dependency failure is a hard stop
    sys.exit("ERROR: jsonschema is not installed (pip install pyyaml jsonschema).")


MARKER = "GENERATED by scripts/sync_agents.py — edit personas/, not this file"

WRAP = 72

CLAUDE = "claude-code"
ANTIGRAVITY = "antigravity"

# Every value here is a NAME or a pattern, never a credential.
SECRET_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"/home/"), "absolute home path"),
    (re.compile(r"/Users/"), "absolute home path"),
    (re.compile(r"\$HOME/|~/\."), "home-relative path"),
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{16,}"), "GitHub token"),
    (re.compile(r"\bgithub_pat_[A-Za-z0-9_]{16,}"), "GitHub fine-grained token"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "AWS access key id"),
    (re.compile(r"\bsk-[A-Za-z0-9]{20,}"), "API secret key"),
    (re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}"), "Slack token"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"), "private key block"),
    # An inline credential VALUE: mixed-case/digit blob after a
    # credential-ish key. All-caps secret NAMES (ATHENA_BOT_TOKEN) are
    # deliberately allowed — declaring the name is the point (D6 of #1).
    (
        re.compile(
            r"(?i)\b(password|secret|api[_-]?key|token)\s*[:=]\s*"
            r"['\"]?(?=[A-Za-z0-9/+_.-]*[a-z0-9])[A-Za-z0-9/+_.-]{16,}"
        ),
        "inline credential value",
    ),
]

# Site-specific strings a given machine must never leak (a local account
# name, an internal domain). Supplied at RUN time as a comma-separated
# list in SYNC_AGENTS_DENY, deliberately never committed: writing the
# thing you are hiding into a public repository defeats the check.
for _literal in filter(None, (s.strip() for s in os.environ.get("SYNC_AGENTS_DENY", "").split(","))):
    SECRET_PATTERNS.append(
        (re.compile(re.escape(_literal), re.IGNORECASE), "denied local string")
    )


class BuildError(Exception):
    """A source or config problem the operator must fix. One per message."""


# --- Load ---------------------------------------------------------------------


def read_yaml(path: Path) -> dict:
    if not path.is_file():
        raise BuildError(f"{path}: missing (the build needs it).")
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise BuildError(f"{path}: not valid YAML — {exc}") from exc
    if not isinstance(data, dict):
        raise BuildError(f"{path}: expected a YAML mapping at the top level.")
    return data


def load_personas(root: Path) -> list[dict]:
    """Every personas/*.yaml, schema-validated, sorted by name."""
    persona_dir = root / "personas"
    schema_path = persona_dir / "schema.json"
    if not persona_dir.is_dir():
        raise BuildError(f"{persona_dir}: no persona sources found.")
    if not schema_path.is_file():
        raise BuildError(f"{schema_path}: missing — nothing to validate against.")
    try:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise BuildError(f"{schema_path}: not valid JSON — {exc}") from exc
    validator = jsonschema.Draft202012Validator(schema)

    sources = sorted(p for p in persona_dir.glob("*.yaml"))
    if not sources:
        raise BuildError(f"{persona_dir}: no *.yaml sources found.")

    personas: list[dict] = []
    for path in sources:
        data = read_yaml(path)
        errors = sorted(validator.iter_errors(data), key=lambda e: list(e.path))
        if errors:
            where = "/".join(str(p) for p in errors[0].path) or "<root>"
            raise BuildError(
                f"{path}: schema violation at {where} — {errors[0].message}"
            )
        if data["name"] != path.stem:
            raise BuildError(
                f"{path}: name '{data['name']}' must equal the filename stem "
                f"'{path.stem}' (personas/schema.json)."
            )
        personas.append(data)

    names = [p["name"] for p in personas]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise BuildError(f"personas/: duplicate actor names {duplicates}.")
    return sorted(personas, key=lambda p: p["name"])


def load_skills(root: Path, personas: list[dict]) -> dict[str, str]:
    """Skill file name -> verbatim text, for every skill any source declares."""
    skills_dir = root / "personas" / "skills"
    texts: dict[str, str] = {}
    for persona in personas:
        for skill in persona.get("skills", []):
            if skill in texts:
                continue
            path = skills_dir / skill
            if not path.is_file():
                raise BuildError(
                    f"personas/{persona['name']}.yaml: declares skill '{skill}' "
                    f"but {path} does not exist."
                )
            texts[skill] = path.read_text(encoding="utf-8").rstrip("\n") + "\n"
    return texts


# The skill whose prompt needs the ladder rendered under it (#36, D3).
# Any source that declares it gets the generated `## Lifecycle stages`
# section; no source may hand-author that table.
RESUME_SKILL = "resume-protocol.md"

LIFECYCLE_KEYS = (
    "stage",
    "label",
    "artifact",
    "advances_on",
    "advances_to",
    "advance_message",
    "dispatch_brief",
)


def load_lifecycle(root: Path) -> list[dict]:
    """personas/lifecycle.json's `stages`, in ladder order (#36, D1/D2).

    Read beside the schema and with the same stdlib, because the ladder
    is data every actor shares: the advancer applies it, the dispatcher
    routes on it, and this compiler renders it into the prompts. There is
    no second copy anywhere, which is the whole point of the file.

    Validates stage names against schema.json's stage enum, label uniqueness,
    terminal and non-terminal advances_to values, and the four advances_on
    invariants (#52 AT-3, #57 D10, Argus F12).
    """
    path = root / "personas" / "lifecycle.json"
    if not path.is_file():
        raise BuildError(f"{path}: missing — the lifecycle ladder has no source.")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise BuildError(f"{path}: not valid JSON — {exc}") from exc
    stages = data.get("stages") if isinstance(data, dict) else None
    if not isinstance(stages, list) or not stages:
        raise BuildError(f"{path}: expected a non-empty 'stages' array.")

    schema_path = root / "personas" / "schema.json"
    if not schema_path.is_file():
        raise BuildError(f"{schema_path}: missing — nothing to validate lifecycle against.")
    try:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise BuildError(f"{schema_path}: not valid JSON — {exc}") from exc

    valid_stages = schema.get("properties", {}).get("stage", {}).get("items", {}).get("enum", [])
    if not valid_stages:
        raise BuildError(f"{schema_path}: no valid stage enum found in schema.")

    valid_advances_on = schema.get("$defs", {}).get("advances_on", {}).get("enum", [])
    if not valid_advances_on:
        raise BuildError(f"{schema_path}: no valid advances_on enum found in schema $defs.")

    for index, row in enumerate(stages):
        if not isinstance(row, dict):
            raise BuildError(f"{path}: stages[{index}] is not an object.")
        missing = [k for k in LIFECYCLE_KEYS if k not in row]
        if missing:
            raise BuildError(
                f"{path}: stages[{index}] is missing {', '.join(missing)}."
            )

    names = [str(row["stage"]) for row in stages]
    duplicates = sorted({n for n in names if names.count(n) > 1})
    if duplicates:
        raise BuildError(f"{path}: duplicate stage rows {duplicates}.")

    for index, row in enumerate(stages):
        stage_val = row["stage"]
        if stage_val not in valid_stages:
            raise BuildError(
                f"{path}: stages[{index}] stage '{stage_val}' is not one of {valid_stages} ({schema_path})."
            )

    labels = [row.get("label") for row in stages]
    duplicate_labels = sorted({l for l in labels if labels.count(l) > 1 and l is not None})
    if duplicate_labels:
        raise BuildError(f"{path}: duplicate label rows {duplicate_labels}.")

    for index, row in enumerate(stages):
        is_last = (index == len(stages) - 1)
        adv_to = row.get("advances_to")
        if is_last:
            if adv_to is not None:
                raise BuildError(
                    f"{path}: stages[{index}] last rung must have advances_to null, got '{adv_to}'."
                )
        else:
            if adv_to is None:
                raise BuildError(
                    f"{path}: stages[{index}] non-terminal rung cannot have advances_to null."
                )

        adv_on = row.get("advances_on")
        if adv_on not in valid_advances_on:
            raise BuildError(
                f"{path}: stages[{index}] invalid advances_on {json.dumps(adv_on)}, "
                f"must be one of {valid_advances_on}."
            )

        art = row.get("artifact")
        if adv_on == "artifact":
            if art is None:
                raise BuildError(
                    f"{path}: stages[{index}] advances_on is 'artifact' but artifact is null."
                )
        else:
            if art is not None:
                raise BuildError(
                    f"{path}: stages[{index}] advances_on is {json.dumps(adv_on)} "
                    f"but artifact is non-null '{art}'."
                )

        if is_last:
            if adv_on is not None:
                raise BuildError(
                    f"{path}: stages[{index}] last rung must have advances_on null, got {json.dumps(adv_on)}."
                )
        else:
            if adv_on is None:
                raise BuildError(
                    f"{path}: stages[{index}] non-terminal rung cannot have advances_on null."
                )

    merge_count = sum(1 for row in stages if row.get("advances_on") == "merge")
    if merge_count != 1:
        raise BuildError(
            f"{path}: expected exactly one rung with advances_on 'merge', found {merge_count}."
        )

    return stages


def stage_owners(personas: list[dict]) -> dict[str, list[str]]:
    """stage -> sorted owning persona names. DERIVED, never stored (D2).

    Ownership is not a column in lifecycle.json: it is whichever sources
    list the stage, so moving a stage between personas edits exactly one
    YAML file.
    """
    owners: dict[str, list[str]] = {}
    for persona in personas:
        for stage in persona.get("stage", []):
            owners.setdefault(str(stage), []).append(persona["name"])
    return {stage: sorted(names) for stage, names in owners.items()}


# --- Resolve ------------------------------------------------------------------


class Resolver:
    """The three config/ lookups. The only place vendor names enter."""

    def __init__(self, root: Path):
        config_dir = root / "config"
        tiers = read_yaml(config_dir / "model_tiers.yaml")
        deployments = read_yaml(config_dir / "deployments.yaml")
        tools = read_yaml(config_dir / "tools.yaml")

        self.harness_models: dict = tiers.get("harnesses") or {}
        if not self.harness_models:
            raise BuildError("config/model_tiers.yaml: no 'harnesses' section.")
        self.pins: dict = deployments.get("personas") or {}
        if not self.pins:
            raise BuildError("config/deployments.yaml: no 'personas' pins.")
        self.capabilities: dict = tools.get("capabilities") or {}
        if not self.capabilities:
            raise BuildError("config/tools.yaml: no 'capabilities' section.")

    def harnesses(self) -> list[str]:
        return sorted(self.harness_models)

    def model(self, tier: str, harness: str, who: str) -> str:
        column = self.harness_models.get(harness)
        if not isinstance(column, dict):
            raise BuildError(
                f"config/model_tiers.yaml: no bindings for harness '{harness}' "
                f"(needed by {who})."
            )
        model = column.get(tier)
        if not model:
            raise BuildError(
                f"config/model_tiers.yaml: harness '{harness}' has no model for "
                f"tier '{tier}' (needed by {who})."
            )
        return str(model)

    def harness_for(self, persona: dict) -> list[str]:
        """Every harness, for every source (D2 as amended 2026-09-10).

        A persona compiles for BOTH harnesses so an operator can start it
        interactively on either one; the pin in deployments.yaml is the
        workflow glue (which harness the dispatcher launches unattended),
        never a limit on where the agent definition exists. The pin is
        still validated here because the dispatcher and the reviewer
        constraint both depend on it.
        """
        name = persona["name"]
        if persona["kind"] == "persona":
            pin = self.pins.get(name)
            if not isinstance(pin, dict) or not pin.get("harness"):
                raise BuildError(
                    f"config/deployments.yaml: persona '{name}' has no harness pin."
                )
            harness = str(pin["harness"])
            if harness not in self.harness_models:
                raise BuildError(
                    f"config/deployments.yaml: persona '{name}' is pinned to unknown "
                    f"harness '{harness}' (model_tiers.yaml knows "
                    f"{sorted(self.harness_models)})."
                )
        return self.harnesses()

    def tools(self, persona: dict, harness: str) -> tuple[list[str], list[tuple[str, str]]]:
        """(concrete tools in declared order, [(capability, fallback text)])."""
        name = persona["name"]
        resolved: list[str] = []
        fallbacks: list[tuple[str, str]] = []
        for capability in persona["capabilities"]:
            cap = capability["name"]
            required = capability.get("required", True)
            entry = self.capabilities.get(cap)
            if entry is None:
                raise BuildError(
                    f"personas/{name}.yaml: capability '{cap}' has no entry in "
                    f"config/tools.yaml."
                )
            mapped = entry.get(harness)
            if mapped:
                for tool in mapped:
                    if tool not in resolved:
                        resolved.append(str(tool))
                continue
            if required:
                raise BuildError(
                    f"personas/{name}.yaml: REQUIRED capability '{cap}' has no "
                    f"tool mapping for harness '{harness}' — add one to "
                    f"config/tools.yaml or mark the capability optional."
                )
            fallback = entry.get("fallback")
            if not fallback:
                raise BuildError(
                    f"config/tools.yaml: optional capability '{cap}' is unmapped "
                    f"for harness '{harness}' and declares no 'fallback' text "
                    f"(needed by personas/{name}.yaml)."
                )
            fallbacks.append((cap, " ".join(str(fallback).split())))
        return resolved, fallbacks


# --- Assemble -----------------------------------------------------------------


def flow(text: str) -> str:
    """Collapse a folded YAML scalar to one line."""
    return " ".join(str(text).split())


def wrap(text: str) -> str:
    return textwrap.fill(flow(text), width=WRAP)


def bullet(text: str) -> str:
    return textwrap.fill(
        flow(text), width=WRAP, initial_indent="- ", subsequent_indent="  "
    )


def describe(role: str) -> str:
    """One-line description derived from the role's first sentence.

    Deterministic rule: take the first sentence; keep appending whole
    sentences only while the result is shorter than 60 characters, so
    that a terse opener ("The product owner.") still says something
    useful in a harness's agent picker.
    """
    sentences = re.split(r"(?<=\.)\s+", flow(role))
    description = sentences[0]
    index = 1
    while len(description) < 60 and index < len(sentences):
        description = f"{description} {sentences[index]}"
        index += 1
    return description


WRITE_LADDER = {
    "none": "no GitHub writes of any kind",
    "comments": (
        "may post comments on issues and pull requests; may not open "
        "issues, push branches, or open pull requests"
    ),
    "issues": (
        "may open issues and post comments; may not push branches or "
        "open pull requests"
    ),
}


def write_ladder(mode: str) -> str:
    if mode.startswith("branch:"):
        glob = mode.split(":", 1)[1]
        return (
            f"may push branches matching `{glob}`, open pull requests from "
            f"them, open issues, and post comments — never the default branch"
        )
    return WRITE_LADDER.get(mode, mode)


def render_body(
    persona: dict,
    fallbacks: list[tuple[str, str]],
    skills: dict[str, str],
    lifecycle: list[dict],
    owners: dict[str, list[str]],
) -> str:
    """The instruction body. Identical across harnesses except for the
    generated fallbacks, which exist only where a harness lacks a tool."""
    name = persona["name"]
    parts: list[str] = [f"# {name}", "", wrap(persona["role"]), ""]

    for skill in persona.get("skills", []):
        parts += [f"## Skill: {skill}", "", skills[skill].rstrip("\n"), ""]

    parts += ["## Authority and bounds", ""]
    if persona["kind"] == "subagent":
        parts += [
            wrap(
                "You are a sub-agent: no GitHub identity, no credential of "
                "your own, and no authority to write to the tracker. You run "
                "inside the harness of the persona that dispatched you, you "
                "may not dispatch sub-agents yourself, and you report back to "
                "that persona rather than acting in the world."
            ),
            "",
        ]
    else:
        authority = persona["authority"]
        bullets = [
            bullet(f"Lifecycle stages owned: {', '.join(persona['stage'])}"),
            bullet(f"GitHub write: {write_ladder(authority['github_write'])}"),
        ]
        if authority.get("paths"):
            bullets.append(
                bullet(
                    "Paths this actor's pull requests may touch: "
                    + ", ".join(f"`{p}`" for p in authority["paths"])
                )
            )
        bullets.append(bullet(f"Acts as GitHub identity: {authority['identity']}"))
        bullets.append(
            bullet(
                f"Credential: the secret NAMED {authority['token']} "
                "(a name, never a value and never a path)"
            )
        )
        if persona.get("delegates_to"):
            bullets.append(
                bullet("May dispatch sub-agents: " + ", ".join(persona["delegates_to"]))
            )
        parts += bullets + [""]
        parts += [
            wrap(
                "These bounds are stated here so this prompt knows them; they "
                "are ENFORCED mechanically by branch protection, merge-gate "
                "path checks, and token scopes — never by this text. An action "
                "that would exceed them is a stop-and-hand-back, not a "
                "judgment call."
            ),
            "",
        ]

    if persona.get("limits"):
        limits = persona["limits"]
        parts += [
            wrap(
                f"Execution caps: at most {limits['max_turns']} turns and "
                f"{limits['timeout_mins']} minutes. Hitting a cap is a handoff, "
                "not a failure — report where you got to."
            ),
            "",
        ]

    if persona.get("escalation_tier"):
        parts += [
            wrap(
                f"Grade: routine work runs at your base grade ({persona['tier']}). "
                f"You may escalate to the {persona['escalation_tier']} grade only "
                "when the work genuinely demands it, and you say so when you do."
            ),
            "",
        ]

    parts += [
        "## Standards",
        "",
        wrap(
            "AGENTS.md at the repository root is the canonical standard for "
            "every actor here: the tracker workflow (pick, claim, read, work, "
            "hand off, gate), the Done/Decided/Next/Blocked handoff comment, "
            "run-folder bookkeeping, the living spec upsert rule, and context "
            "and cost discipline. Read it and follow it. It is referenced, "
            "never duplicated — this prompt does not restate it, and where the "
            "two ever appear to differ, AGENTS.md wins."
        ),
        "",
    ]

    if fallbacks:
        parts += ["## Capability fallbacks", ""]
        parts += [
            wrap(
                "This harness has no native tool for the capabilities below. "
                "The instruction under each is generated from "
                "config/tools.yaml — it is the substitute procedure, and it is "
                "binding."
            ),
            "",
        ]
        for capability, text in fallbacks:
            parts += [f"### {capability}", "", wrap(text), ""]

    # The ladder, GENERATED from personas/lifecycle.json joined against
    # every source's `stage` field (#36, D3). Emitted only where the
    # resume protocol is declared, because only an actor that claims
    # issues needs it — and hand-authoring this table into the skill
    # would be the second copy lifecycle.json exists to prevent.
    if RESUME_SKILL in persona.get("skills", []):
        parts += ["## Lifecycle stages", ""]
        parts += [
            wrap(
                "The ladder below is generated from personas/lifecycle.json, "
                "the single source of the label-to-stage relation, joined "
                "against the stages every actor source declares. An issue's "
                "one `status:*` label names the current stage; work it only "
                "if you are listed as an owner of that stage, and otherwise "
                "name the owner and stop."
            ),
            "",
        ]
        for row in lifecycle:
            stage = str(row["stage"])
            who = owners.get(stage) or []
            parts += [f"### {stage}", ""]
            parts += [
                bullet(f"Current when the issue carries `{row['label']}`"),
                bullet(
                    f"Artifact: `{row['artifact']}`"
                    if row["artifact"]
                    else "Artifact: none — the output is code or a review"
                ),
                bullet(
                    "Owner: " + ", ".join(who)
                    if who
                    else "Owner: none — no actor source declares this stage"
                ),
                bullet(
                    (
                        f"Advances to `{row['advances_to']}` when that "
                        "artifact merges"
                        if row["artifact"]
                        else f"Advances to `{row['advances_to']}` when this "
                        "stage's work merges"
                    )
                    if row["advances_to"]
                    else "Last rung: nothing advances past it automatically"
                ),
                bullet(f"Brief: {row['dispatch_brief']}"),
                "",
            ]

    return "\n".join(parts).rstrip("\n") + "\n"


# --- Emit ---------------------------------------------------------------------


def yaml_scalar(value: str) -> str:
    """A YAML double-quoted scalar. JSON string syntax is a valid subset."""
    return json.dumps(value, ensure_ascii=False)


class ClaudeEmitter:
    """.claude/agents/<name>.md — YAML frontmatter + the assembled body."""

    harness = CLAUDE

    def emit(self, persona: dict, model: str, tools: list[str], body: str) -> dict[str, str]:
        # The marker is the first line INSIDE the frontmatter: Claude Code
        # requires the `---` at byte 0, so a leading comment would break
        # the file it is meant to label.
        frontmatter = [
            "---",
            f"# {MARKER}",
            f"name: {persona['name']}",
            f"description: {yaml_scalar(describe(persona['role']))}",
            f"tools: {', '.join(tools)}",
            f"model: {model}",
            "---",
            "",
        ]
        return {
            f".claude/agents/{persona['name']}.md": "\n".join(frontmatter) + body
        }


class AntigravityEmitter:
    """.agents/agents/<name>/{agent.md,agent.json}.

    agy reads ONLY agent.md: YAML frontmatter plus the markdown body,
    exactly as `.claude/agents/<name>.md` is shaped for Claude Code.
    Two keys are load-bearing by measurement (#43, findings Q1b and
    this issue's probes P1/P1a/P2):

    * `model:` in the frontmatter VOIDS the agent — agy silently falls
      back to its stock agent and still exits 0. So the resolved model
      never appears here; it rides in the sidecar (D9) and reaches the
      CLI as `--model`.
    * an unrecognised name in `tools:` is a HARD error (exit 1), which
      is why the list is the harness-mapped one from config/tools.yaml
      and never the Claude spelling.

    agent.json is a machine-readable sidecar that agy ignores (P2:
    discovery is unaffected by its presence). It carries the two facts
    agent.md cannot: the resolved model and the sub-agent flag. Limits
    are NOT copied here — they live in personas/<name>.yaml and
    scripts/ops/work.sh reads them there, so each fact has one home.
    """

    harness = ANTIGRAVITY

    def emit(self, persona: dict, model: str, tools: list[str], body: str) -> dict[str, str]:
        name = persona["name"]
        base = f".agents/agents/{name}"
        # The marker is the first line INSIDE the frontmatter, as in
        # ClaudeEmitter: agy wants the `---` at byte 0 too, and probe P1
        # measured that a YAML comment there does not void the agent.
        frontmatter = [
            "---",
            f"# {MARKER}",
            f"name: {name}",
            f"description: {yaml_scalar(describe(persona['role']))}",
            "tools:",
        ]
        frontmatter += [f"  - {tool}" for tool in tools]
        frontmatter += ["---", ""]
        agent = {
            "_generated": MARKER,
            "model": model,
            "name": name,
            "subagent": persona["kind"] == "subagent",
        }
        return {
            f"{base}/agent.md": "\n".join(frontmatter) + body,
            f"{base}/agent.json": json.dumps(
                agent, indent=2, sort_keys=True, ensure_ascii=False
            )
            + "\n",
        }


EMITTERS = {CLAUDE: ClaudeEmitter(), ANTIGRAVITY: AntigravityEmitter()}

TARGET_DIRS = (".claude/agents", ".agents/agents")


# --- Sanitize -----------------------------------------------------------------


def sanitize(relpath: str, content: str) -> None:
    for pattern, label in SECRET_PATTERNS:
        match = pattern.search(content)
        if match:
            line = content[: match.start()].count("\n") + 1
            raise BuildError(
                f"REFUSING TO WRITE {relpath}: line {line} looks like a "
                f"{label} ({match.group(0)[:24]!r}). Fix the source under "
                f"personas/ or config/ — the compiler never emits it."
            )
    if any(pattern.search(relpath) for pattern, _ in SECRET_PATTERNS):
        raise BuildError(f"REFUSING TO WRITE {relpath}: output path looks unsafe.")


# --- Build --------------------------------------------------------------------


def compile_all(root: Path) -> list[dict]:
    """The whole pipeline, in memory. One record per persona x harness."""
    personas = load_personas(root)
    skills = load_skills(root, personas)
    lifecycle = load_lifecycle(root)
    owners = stage_owners(personas)
    resolver = Resolver(root)

    records: list[dict] = []
    seen: set[str] = set()
    for persona in personas:
        for harness in resolver.harness_for(persona):
            emitter = EMITTERS.get(harness)
            if emitter is None:
                raise BuildError(
                    f"personas/{persona['name']}.yaml resolves to harness "
                    f"'{harness}', which has no emitter. Add one to "
                    f"scripts/sync_agents.py."
                )
            who = f"personas/{persona['name']}.yaml on {harness}"
            model = resolver.model(persona["tier"], harness, who)
            tools, fallbacks = resolver.tools(persona, harness)
            body = render_body(persona, fallbacks, skills, lifecycle, owners)
            files = emitter.emit(persona, model, tools, body)
            for relpath, content in files.items():
                if relpath in seen:
                    raise BuildError(f"two sources both emit {relpath}.")
                seen.add(relpath)
                sanitize(relpath, content)
            records.append(
                {
                    "persona": persona,
                    "harness": harness,
                    "model": model,
                    "tools": tools,
                    "fallbacks": fallbacks,
                    "skills": {s: skills[s] for s in persona.get("skills", [])},
                    "lifecycle": (
                        [str(row["stage"]) for row in lifecycle]
                        if RESUME_SKILL in persona.get("skills", [])
                        else []
                    ),
                    "files": files,
                }
            )
    return records


def existing_generated(out: Path) -> dict[str, str]:
    """Committed files under the target dirs that this compiler owns."""
    found: dict[str, str] = {}
    for target in TARGET_DIRS:
        base = out / target
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            try:
                content = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if MARKER in content:
                found[path.relative_to(out).as_posix()] = content
    return found


def write(files: dict[str, str], out: Path) -> tuple[int, int, int]:
    """Write, prune stale generated files, return (written, unchanged, pruned)."""
    stale = set(existing_generated(out)) - set(files)
    written = unchanged = 0
    for relpath, content in files.items():
        path = out / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            unchanged += 1
            continue
        path.write_text(content, encoding="utf-8")
        written += 1
    for relpath in sorted(stale):
        (out / relpath).unlink()
    for target in TARGET_DIRS:
        base = out / target
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*"), reverse=True):
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    return written, unchanged, len(stale)


def check(files: dict[str, str], out: Path) -> int:
    """Diff a fresh build against the committed targets. 0 = clean."""
    committed = existing_generated(out)
    drift: list[str] = []
    for relpath, content in files.items():
        if relpath not in committed:
            drift.append(f"  MISSING   {relpath} (never committed)")
        elif committed[relpath] != content:
            drift.append(f"  STALE     {relpath} (committed copy differs)")
    for relpath in sorted(set(committed) - set(files)):
        drift.append(f"  ORPHANED  {relpath} (no source emits it)")
    if drift:
        print("DRIFT: compiled targets do not match personas/ + config/:")
        print("\n".join(sorted(drift)))
        print("\nRun: python3 scripts/sync_agents.py  — then commit the result.")
        return 1
    print(f"OK: {len(files)} compiled targets match personas/ + config/.")
    return 0


# --- Verify (roundtrip) -------------------------------------------------------


def read_frontmatter(path: Path) -> tuple[dict, str]:
    """Split a compiled agent markdown file into (frontmatter, body).

    Generic across harnesses: `.claude/agents/<name>.md` and
    `.agents/agents/<name>/agent.md` share the layout.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise BuildError(f"{path}: no YAML frontmatter at the start of the file.")
    _, _, rest = text.partition("---\n")
    head, sep, body = rest.partition("\n---\n")
    if not sep:
        raise BuildError(f"{path}: frontmatter is not terminated by '---'.")
    parsed = yaml.safe_load(head)
    if not isinstance(parsed, dict):
        raise BuildError(f"{path}: frontmatter did not parse as a mapping.")
    return parsed, body


def verify(records: list[dict], out: Path) -> int:
    """Re-parse the targets ON DISK and assert they carry what was resolved.

    Independent of the in-memory build: this reads the emitted bytes back
    and checks the resolved model, the mapped tools, and the full text of
    every declared skill actually survived compilation.
    """
    problems: list[str] = []

    def require(condition: bool, message: str) -> None:
        if not condition:
            problems.append(f"  {message}")

    for record in records:
        persona = record["persona"]
        name = persona["name"]
        harness = record["harness"]
        tag = f"{name} @ {harness}"

        if harness == CLAUDE:
            path = out / f".claude/agents/{name}.md"
            require(path.is_file(), f"{tag}: {path} was not emitted")
            if not path.is_file():
                continue
            front, body = read_frontmatter(path)
            require(front.get("name") == name, f"{tag}: frontmatter name is wrong")
            require(
                front.get("model") == record["model"],
                f"{tag}: model is {front.get('model')!r}, expected "
                f"{record['model']!r}",
            )
            emitted_tools = [t.strip() for t in str(front.get("tools", "")).split(",")]
            require(
                emitted_tools == record["tools"],
                f"{tag}: tools are {emitted_tools}, expected {record['tools']}",
            )
            require(
                bool(str(front.get("description", "")).strip()),
                f"{tag}: frontmatter carries no description",
            )
        else:
            base = out / f".agents/agents/{name}"
            for leaf in ("agent.md", "agent.json"):
                require((base / leaf).is_file(), f"{tag}: {base / leaf} not emitted")
            if not ((base / "agent.md").is_file() and (base / "agent.json").is_file()):
                continue
            agent = json.loads((base / "agent.json").read_text(encoding="utf-8"))
            require(agent.get("name") == name, f"{tag}: agent.json name is wrong")
            require(
                agent.get("model") == record["model"],
                f"{tag}: model is {agent.get('model')!r}, expected "
                f"{record['model']!r}",
            )
            require(
                agent.get("subagent") == (persona["kind"] == "subagent"),
                f"{tag}: agent.json subagent flag does not match kind",
            )
            front, body = read_frontmatter(base / "agent.md")
            require(front.get("name") == name, f"{tag}: agent.md name is wrong")
            # A `model:` key here voids the agent for agy and it falls
            # back silently, exit 0 (#43 D8, findings Q1b). The compiler
            # is the only writer of this file, so this assertion is what
            # keeps that failure impossible rather than merely unlikely.
            require("model" not in front, f"{tag}: agent.md must carry no model key")
            require(
                front.get("tools") == record["tools"],
                f"{tag}: tools are {front.get('tools')}, expected {record['tools']}",
            )
            require(
                bool(str(front.get("description", "")).strip()),
                f"{tag}: agent.md carries no description",
            )

        for skill, text in record["skills"].items():
            require(
                text.rstrip("\n") in body,
                f"{tag}: skill '{skill}' is not inlined in full",
            )
        for capability, text in record["fallbacks"]:
            require(
                f"### {capability}" in body,
                f"{tag}: no generated fallback section for '{capability}'",
            )
            require(
                flow(text)[:40] in flow(body),
                f"{tag}: fallback text for '{capability}' is missing",
            )
        # A target that declares the resume protocol must carry the WHOLE
        # generated ladder, not just the rungs it owns: refusing a stage
        # means naming that stage's owner, and it can only do that from
        # this block (#36, D3, D5(f)).
        if record["lifecycle"]:
            require(
                "## Lifecycle stages" in body,
                f"{tag}: declares {RESUME_SKILL} but carries no generated ladder",
            )
        for stage in record["lifecycle"]:
            require(
                f"### {stage}" in body,
                f"{tag}: generated ladder is missing stage '{stage}'",
            )
        for relpath in record["files"]:
            content = (out / relpath).read_text(encoding="utf-8")
            require(MARKER in content, f"{tag}: {relpath} carries no generated marker")

    if problems:
        print("VERIFY FAILED: emitted targets do not carry the resolved facts:")
        print("\n".join(problems))
        return 1
    print(
        f"OK: {len(records)} compiled agents carry their resolved model, "
        f"mapped tools, and full skill text."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Compile personas/ + config/ into harness agent targets."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="source tree holding personas/ and config/ (default: repo root)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="output tree for the compiled targets (default: --root)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="rebuild and diff against the committed targets without touching "
        "them; exit 1 on drift (the CI drift gate)",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="re-parse the emitted targets on disk and assert each carries its "
        "resolved model, mapped tools, and full skill text; exit 1 on failure",
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    out = (args.out or args.root).resolve()

    try:
        records = compile_all(root)
        files: dict[str, str] = {}
        for record in records:
            files.update(record["files"])
        files = dict(sorted(files.items()))

        if args.check:
            return check(files, out)
        if args.verify:
            return verify(records, out)
    except BuildError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    # Nothing touches the filesystem until the whole build has succeeded
    # and every file has passed the sanitizer, so a bad source can never
    # leave half-compiled targets behind.
    written, unchanged, pruned = write(files, out)
    print(
        f"Compiled {len(files)} targets into {out} "
        f"({written} written, {unchanged} unchanged, {pruned} pruned)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
